=== loft-sh/tunnel/examples/coordinator/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/Config",
  "$defs": {
    "Config": {
      "properties": {
        "httpListenAddr": {
          "type": "string"
        },
        "controlKey": {
          "$ref": "#/$defs/MachinePrivate"
        },
        "controlKeyLocation": {
          "type": "string"
        },
        "legacyControlKey": {
          "$ref": "#/$defs/MachinePrivate"
        },
        "legacyControlKeyLocation": {
          "type": "string"
        },
        "baseDomain": {
          "type": "string"
        },
        "cidr": {
          "type": "string"
        },
        "keepAliveInterval": {
          "type": "integer"
        },
        "derpMap": {
          "$ref": "#/$defs/DERPMap"
        },
        "extraRecords": {
          "items": {
            "$ref": "#/$defs/DNSRecord"
          },
          "type": "array"
        },
        "userProfiles": {
          "items": {
            "$ref": "#/$defs/UserProfile"
          },
          "type": "array"
        },
        "nodes": {
          "items": {
            "properties": {
              "nodeKey": {
                "type": "string"
              },
              "peerPublicKey": {
                "type": "string"
              },
              "userId": {
                "type": "integer"
              },
              "nodeId": {
                "type": "integer"
              },
              "ip": {
                "type": "string"
              }
            },
            "additionalProperties": false,
            "type": "object",
            "required": [
              "nodeKey",
              "peerPublicKey",
              "userId",
              "nodeId"
            ]
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "baseDomain",
        "cidr",
        "userProfiles"
      ]
    },
    "DERPHomeParams": {
      "properties": {
        "RegionScore": {
          "patternProperties": {
            "^[0-9]+$": {
              "type": "number"
            }
          },
          "additionalProperties": false,
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "DERPMap": {
      "properties": {
        "HomeParams": {
          "$ref": "#/$defs/DERPHomeParams"
        },
        "Regions": {
          "patternProperties": {
            "^[0-9]+$": {
              "$ref": "#/$defs/DERPRegion"
            }
          },
          "additionalProperties": false,
          "type": "object"
        },
        "omitDefaultRegions": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "Regions"
      ]
    },
    "DERPNode": {
      "properties": {
        "Name": {
          "type": "string"
        },
        "RegionID": {
          "type": "integer"
        },
        "HostName": {
          "type": "string"
        },
        "CertName": {
          "type": "string"
        },
        "IPv4": {
          "type": "string"
        },
        "IPv6": {
          "type": "string"
        },
        "STUNPort": {
          "type": "integer"
        },
        "STUNOnly": {
          "type": "boolean"
        },
        "DERPPort": {
          "type": "integer"
        },
        "InsecureForTests": {
          "type": "boolean"
        },
        "STUNTestIP": {
          "type": "string"
        },
        "CanPort80": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "Name",
        "RegionID",
        "HostName"
      ]
    },
    "DERPRegion": {
      "properties": {
        "RegionID": {
          "type": "integer"
        },
        "RegionCode": {
          "type": "string"
        },
        "RegionName": {
          "type": "string"
        },
        "Avoid": {
          "type": "boolean"
        },
        "Nodes": {
          "items": {
            "$ref": "#/$defs/DERPNode"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "RegionID",
        "RegionCode",
        "RegionName",
        "Nodes"
      ]
    },
    "DNSRecord": {
      "properties": {
        "Name": {
          "type": "string"
        },
        "Type": {
          "type": "string"
        },
        "Value": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "Name",
        "Value"
      ]
    },
    "MachinePrivate": {
      "properties": {},
      "additionalProperties": false,
      "type": "object"
    },
    "UserProfile": {
      "properties": {
        "ID": {
          "type": "integer"
        },
        "LoginName": {
          "type": "string"
        },
        "DisplayName": {
          "type": "string"
        },
        "ProfilePicURL": {
          "type": "string"
        },
        "Roles": {
          "$ref": "#/$defs/emptyStructJSONSlice"
        },
        "Groups": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "ID",
        "LoginName",
        "DisplayName",
        "ProfilePicURL",
        "Roles"
      ]
    },
    "emptyStructJSONSlice": {
      "properties": {},
      "additionalProperties": false,
      "type": "object"
    }
  }
}

=== loft-sh/tunnel/examples/coordinator/config.json
{
  "httpListenAddr": ":3000",

  "controlKeyLocation": "tmp/control.key",
  "legacyControlKeyLocation": "tmp/legacy.key",
  "baseDomain": "ts.loft",
  "cidr": "100.64.0.0/10",

  "userProfiles": [
    {
      "ID": 100,
      "DisplayName": "Test User",
      "LoginName": "testuser",
      "Groups": ["testgroup"],
      "ProfilePicURL": "",
      "Roles": {}
    },
    {
      "ID": 200,
      "DisplayName": "Another Test User",
      "LoginName": "another-testuser",
      "Groups": ["anoter-testgroup"],
      "ProfilePicURL": "",
      "Roles": {}
    }
  ],

  "nodes": [
    {
      "nodeId": 1,
      "userId": 100,
      "nodeKey":  "nodekey:114c3b606b1f35b4b59b46f21bb9bb8ce7498541adf5feb178a6f57bc71e4864",
      "peerPublicKey": "mkey:ec7971b903bf82bb2fbe6af6b041171fd976c44e7c60ddf2f148e44ba5711417",
      "ip": "100.100.200.200"
    }
  ]
}
